version: "3.8"

services:
  kafka1:
    image: bitnami/kafka:3.8.0
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: PVjHlx7ESeesq55jeB6Efw
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9091,2@kafka2:9091,3@kafka3:9091'
      KAFKA_CFG_LISTENERS: CONTROLLER://:9091,SSL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: SSL://kafka1:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SSL:SSL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.keystore.jks
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.truststore.jks
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_CFG_SSL_KEY_PASSWORD: changeit
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_TLS_TYPE: JKS
      ALLOW_PLAINTEXT_LISTENER: no
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-1.0.1.jar=7072:/usr/share/jmx_exporter/kafka.yml"
      #KAFKA_OPTS: "-Djavax.net.debug=ssl,handshake"
    volumes:
      - ./jmx_exporter/:/usr/share/jmx_exporter
      - ./kraft/server1/:/bitnami/kafka
      - ./secrets/kafka1:/bitnami/kafka/config/certs
    restart: always

  kafka2:
    image: bitnami/kafka:3.8.0
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_KRAFT_CLUSTER_ID: PVjHlx7ESeesq55jeB6Efw
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9091,2@kafka2:9091,3@kafka3:9091'
      KAFKA_CFG_LISTENERS: CONTROLLER://:9091,SSL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: SSL://kafka2:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SSL:SSL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.keystore.jks
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.truststore.jks
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_CFG_SSL_KEY_PASSWORD: changeit
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_TLS_TYPE: JKS
      ALLOW_PLAINTEXT_LISTENER: no
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-1.0.1.jar=7073:/usr/share/jmx_exporter/kafka.yml"
      #KAFKA_OPTS: "-Djavax.net.debug=ssl,handshake"
    volumes:
      - ./jmx_exporter/:/usr/share/jmx_exporter
      - ./kraft/server2/:/bitnami/kafka
      - ./secrets/kafka2:/bitnami/kafka/config/certs
    restart: always

  kafka3:
    image: bitnami/kafka:3.8.0
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 3
      KAFKA_KRAFT_CLUSTER_ID: PVjHlx7ESeesq55jeB6Efw
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9091,2@kafka2:9091,3@kafka3:9091'
      KAFKA_CFG_LISTENERS: CONTROLLER://:9091,SSL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: SSL://kafka3:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SSL:SSL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.keystore.jks
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.truststore.jks
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_CFG_SSL_KEY_PASSWORD: changeit
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_TLS_TYPE: JKS
      ALLOW_PLAINTEXT_LISTENER: no
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-1.0.1.jar=7074:/usr/share/jmx_exporter/kafka.yml"
      #KAFKA_OPTS: "-Djavax.net.debug=ssl,handshake"
    volumes:
      - ./jmx_exporter/:/usr/share/jmx_exporter
      - ./kraft/server3/:/bitnami/kafka
      - ./secrets/kafka3:/bitnami/kafka/config/certs
    restart: always

  akhq:
    image: tchiotludo/akhq:0.25.1
    container_name: akhq  #UI for Kafka
    ports:
      - "8080:8080"  # Порт для доступа к UI
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka1:9092,kafka2:9093,kafka3:9094"
                security.protocol: SSL
                ssl.truststore.location: /certs/truststore.jks
                ssl.truststore.password: changeit
                ssl.keystore.location: /certs/akhq.keystore.jks
                ssl.keystore.password: changeit
                ssl.key.password: changeit
    volumes:
      - ./secrets/akhq:/certs
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: always

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.8.0
    container_name: kafka_exporter
    command:
      - "--kafka.server=kafka1:9092"
      - "--kafka.server=kafka2:9093"
      - "--kafka.server=kafka3:9094"
      - "--tls.enabled"
      - "--tls.ca-file=/certs/chain.crt"
      - "--tls.cert-file=/certs/kafka_exporter.crt"
      - "--tls.key-file=/certs/kafka_exporter.key"
    ports:
      - "9308:9308"
    environment:
      KAFKA_SERVER: "kafka1:9092,kafka2:9093,kafka3:9094" # Адреса Kafka-брокера
    volumes:
      - ./secrets/kafka_exporter:/certs
    restart: always

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./secrets/prometheus:/etc/prometheus/certs/
    restart: always

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    container_name: producer
    environment:
      RUST_LOG: debug
    volumes:
      - ./secrets/producer:/app/producer
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: always

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    container_name: consumer
    environment:
      RUST_LOG: debug
    volumes:
      - ./secrets/consumer:/app/consumer
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: always

networks:
  default:
    external: false


