[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version =  "1.39.3", features = ["rt-multi-thread", "macros"] }
rdkafka = { version =  "0.36.2", features = ["cmake-build"] }
tokio-stream = "0.1.15"